name = "Old Days"
author = "Ambos"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0501e2fb8916cb4cee7dfb0311de444c08818ff6bff529748f5c10821bcf268d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
